### ISSUE TITLE
Any plans for Ambiant-MATE/Radiant-MATE?

### ISSUE THREAD

**Issue by zara1193** [lah7/ubuntu-mate-colours#32]
I know that those themes are considered deprecated upstream now, but I was curious if you have any plans to work more with them in the future. As much as I'm growing to like the new Yaru themes, I really prefer the skeuomorphic design of the Ambiance theme family and it would be nice to see them continued in some way.

**Comment by lah7** [comment]
I like Ambiant-MATE and skeuomorphic in general too. I still use the theme on an Arch MATE desktop for a work environment.

It crossed my mind whether to fork them, so that colours can be deeply integrated into the theme, and a new point for reporting issues. Right now, I couldn't make a commitment to maintaining them. GTK themes ain't my strength nor much fun for me. 😴 (especially a GTK 4 port, no way!)

This project will always support them for colouring. I believe Ubuntu MATE would _probably_ accept fixes, but the team themselves won't be working on them. If/when they ever disappear from `ubuntu-mate-artwork` then that's probably the time to fork.

**Comment by zara1193** [comment]
Thank you for the insight! Glad I'm not the only fan of these themes, haha.

**Comment by lah7** [comment]
Well, it's official - [[1]](https://github.com/ubuntu-mate/ubuntu-mate-artwork/commit/55274b27cb361527d621e30c89d27efe0453bf7a) [[2]](https://github.com/ubuntu-mate/ubuntu-mate-artwork/commit/1ed40c3c6366accd3b6bea4783bb8fba610a1140) [[3]](https://discord.com/channels/712850672223125565/775655177188933652/955394494344351804) - Ambiant/Radiant-MATE are no longer supported in 22.04 and have been removed. Makes sense since these themes haven't actually had any actual code changes for 2 years.

I preserved and cleaned up the history into a new fork here - I'll do some housekeeping in the next day or two:

⭐  https://github.com/lah7/Ambiant-MATE

**Comment by zara1193** [comment]
> Well, it's official - [[1]](https://github.com/ubuntu-mate/ubuntu-mate-artwork/commit/55274b27cb361527d621e30c89d27efe0453bf7a) [[2]](https://github.com/ubuntu-mate/ubuntu-mate-artwork/commit/1ed40c3c6366accd3b6bea4783bb8fba610a1140) [[3]](https://discord.com/channels/712850672223125565/775655177188933652/955394494344351804) - Ambiant/Radiant-MATE are no longer supported in 22.04 and have been removed. Makes sense since these themes haven't actually had any actual code changes for 2 years.
> 
> I preserved and cleaned up the history into a new fork here - I'll do some housekeeping in the next day or two:
> 
> star https://github.com/lah7/Ambiant-MATE

It's sad to hear that, but I was expecting it. Thanks so much for making a fork, I'll see what I can do about contributing fixes when I have the time to learn more about it.
